spring:
  datasource:
    url: ${DB_CONNECTION_URL}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
