version: "3.7"
services:
  database:
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: ssafy_web_db
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ssafy
      TZ: Asia/Seoul

    volumes:
      - ./db/data:/var/lib/mysql
      - ./src/main/resource:/docker-entrypoint-initdb.d

    ports:
      - 3306:3306

    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

    restart: always

  application:
    build: .
    ports:
      - 9090:9090
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ssafy_web_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafy

    restart: always
